services:
  - type: web
    name: twinskill-backend
    env: node
    buildCommand: npm install && npm run rebuild
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MONGODB_URI
        sync: false
      - key: DID_API_KEY
        sync: false